export const data = [
    {
        id:1,
        name: "Pradhan Mantri Jan Arogya Yojana (PM JAY)",
        desc: "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana is a national public health insurance fund of the Government of India that aims to provide free access to health insurance coverage for low income earners in the country. Roughly, the bottom 50% of the count ry qualifies for this scheme",
        department: "",
        eligibility: "",
        requiredDocuments: "",
        link : "https://setu.pmjay.gov.in/setu/",
        img: "https://th.bing.com/th/id/R.823c8c96913e08549ac510ce540ba2da?rik=yLnIgw%2bDaDs0rQ&riu=http%3a%2f%2fegov.eletsonline.com%2fwp-content%2fuploads%2f2015%2f09%2fWebsite_Logo.png&ehk=G5t2Sv6G7OuIridiCKt%2bNnf8sJ9cor2BXlD4eBYZEzo%3d&risl=&pid=ImgRaw&r=0",
    },
    {
        id:2,
        name: "Pradhan Mantri Awas Yojana (Urban) PMAY (U)",
        desc: "Pradhan Mantri Awas Yojana (Urban) Mission launched on 25th June 2015 which intends to provide housing for all in urban areas by year 2022. The Mission provides Central Assistance to the implementing agencies through States/Union Territories (UTs)",
        department: "",
        eligibility: "",
        requiredDocuments: "",
        link : "https://setu.pmjay.gov.in/setu/",
        img: "https://gudstory.s3.us-east-2.amazonaws.com/wp-content/uploads/2018/12/06202955/Pradhan-Mantri-Awas-Yojana.jpg",
    },
    {
        id:3,
        name: "Atal pension y ojana",
        desc: "A defined pen sion system for the poor and under privileged depending on t he contribution made by su bscriber a nd its period.",
        department: "",
        eligibility: "",
        requiredDocuments: "",
        link : "https://setu.pmjay.gov.in/setu/",
        img: "https://www.ssbcrack.com/wp-content/uploads/2016/05/download-1.png",
    },
    {
        id:4,
        name: "Financial Assi stance for class 1 st to 10 th",
        desc: "Educat ional Assi stance of Rs 2500 to the children studying in 1 st to 7 th std. and Rs 5000 for the children stud ying in 8 th std. ti 10 th of the regist ered wor ker.",
        department: "",
        eligibility: "",
        requiredDocuments: "",
        link : "https://setu.pmjay.gov.in/setu/",
        img: "https://th.bing.com/th/id/OIP.fj-VsdrRpZpCNuTHIdSj0QHaEB?pid=ImgDet&rs=1",
    },
    {
        id:5,
        name: "Pradhan Mantri Jan Arogya Yojana (PM JAY)",
        desc: "Pradhan Mantri Shram Yogi Maandhan is a government scheme meant for old age protection and social security of Unorganized workers",
        department: "",
        eligibility: "",
        requiredDocuments: "",
        link : "https://setu.pmjay.gov.in/setu/",
        img: "https://i2.wp.com/govinfo.me/wp-content/uploads/2017/03/rajasthan-government-logo.png?ssl=1",
    },
    
];