export const data = [
  {
    id: 0,
    title: "Centrally Sponsored Pre Matric Scholarship Scheme for SC Students, Jammu and Kashmir 2022",
    description: "Centrally Sponsored Pre Matric Scholarship Scheme for SC Students, Jammu and Kashmir 2022 is an initiative of the Department of Social Justice & Empowerment, Government of India for students from Class 1 to 10. The objective of this scheme is to support the education of SC students to eliminate the incidence of dropout, especially during the transition from elementary to the secondary stage. The selected students will receive an academic allowance and other benefits.",
    department: "",
    category: "Education",
    eligibility: [
      "be an Indian National",
      "be studying in Class 9 and 10",
      "belong to the SC community of Jammu and Kashmir",
      "have an annual income of INR 2.5 lakh per annum from all sources",
    ],
    benefits: [
      "Component 1- INR 7,000 per annum",
      "Component 2- INR. 8,000 per annum (For Class 3 to 10)",
      "A 10% extra allowance will be given to Divyang (Disabled) students.",
    ],
    requiredDocuments: [
      "A certificate from District Social Welfare officer/ identified officer of Local body/Civic Agency/any such authority as designated by State Government",
      "Income certificate",
      "Markesheets/certificates",
    ],
    steps: [
      `Click on the 'Apply Now' link below.`,
      "Navigate to 'Applicant Corner' and click on 'New Registration'. ",
      "Now click on 'Click here for other Scholarship Schemes hosted on NSP for AY 2022-23'. ",
      "Read the guidelines carefully, select the undertaking, and 'Continue'.",
      "Select the state of domicile, scholarship category (Pre Matric), scheme type (scholarship scheme), gender, and write the applicant's name, date of birth, mobile number, and email ID.",
      "Provide the bank details (Bank name, IFSC Code, Account Number)",
      "Select Aadhaar or Bank Account Number as identification detail and click on the 'Register' button.",
      "The mobile number will be verified and an OTP will be generated.",
      "Now, log in using OTP and fill out the application form.",
      "After successful submission of the application form, an application ID and password will be generated which can be used for future references.",
    ],
    flare:
      "https://d2w7l1p59qkl0r.cloudfront.net/static/Files/banner/Website-banner-hdfc_rFmCRV.webp",
    link: "https://setu.pmjay.gov.in/setu/",
    img: "https://th.bing.com/th/id/R.dae2c75e334ebb1ea22eba62a2d12bb8?rik=S2tUyWHmPOxadw&riu=http%3a%2f%2fwww.logopeople.in%2fblog%2fwp-content%2fuploads%2f2013%2f01%2fgovernment-of-india.jpg&ehk=8h1%2buC9HX1YcrVd6JIC0BBPcVPD0szCYx9TtrLga%2fqM%3d&risl=&pid=ImgRaw&r=0",
    note: "All the applicants are advised to fill the form correctly, no changes can be made once submitted. The applicants are also advised to fill in only one application as multiple applications will cancel the form.",
  },
  {
    id: 1,
    title: "Pradhan Mantri Jan Arogya Yojana (PM JAY)",
    description: "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana is a national public health insurance fund of the Government of India that aims to provide free access to health insurance coverage for low income earners in the country. Roughly, the bottom 50% of the count ry qualifies for this scheme",
    department: "",
    category: "Female",
    eligibility: "",
    requiredDocuments: "",
    flare:
      "https://d2w7l1p59qkl0r.cloudfront.net/static/Files/banner/Website-banner-sbi-foundation_cpqDme.webp",
    link: "https://setu.pmjay.gov.in/setu/",
    img: "https://th.bing.com/th/id/R.823c8c96913e08549ac510ce540ba2da?rik=yLnIgw%2bDaDs0rQ&riu=http%3a%2f%2fegov.eletsonline.com%2fwp-content%2fuploads%2f2015%2f09%2fWebsite_Logo.png&ehk=G5t2Sv6G7OuIridiCKt%2bNnf8sJ9cor2BXlD4eBYZEzo%3d&risl=&pid=ImgRaw&r=0",
  },
  {
    id: 2,
    title: "Pradhan Mantri Awas Yojana (Urban) PMAY (U)",
    description: "Pradhan Mantri Awas Yojana (Urban) Mission launched on 25th June 2015 which intends to provide housing for all in urban areas by year 2022. The Mission provides Central Assistance to the implementing agencies through States/Union Territories (UTs)",
    department: "",
    category: "Farmer",
    eligibility: "",
    flare:
      "https://d2w7l1p59qkl0r.cloudfront.net/static/Files/banner/Website-banner-colgate-banner_RBvlG4.webp",
    requiredDocuments: "",
    link: "https://setu.pmjay.gov.in/setu/",
    img: "https://gudstory.s3.us-east-2.amazonaws.com/wp-content/uploads/2018/12/06202955/Pradhan-Mantri-Awas-Yojana.jpg",
  },
  {
    id: 3,
    title: "Atal pension y ojana",
    description: "A defined pen sion system for the poor and under privileged depending on t he contribution made by su bscriber a nd its period.",
    department: "",
    category: "Employee",
    eligibility: "",
    flare:
      "https://d2w7l1p59qkl0r.cloudfront.net/static/scholarships/banners/document_1675084417.jpg",
    requiredDocuments: "",
    link: "https://setu.pmjay.gov.in/setu/",
    img: "https://www.ssbcrack.com/wp-content/uploads/2016/05/download-1.png",
  },
  {
    id: 4,
    title: "Financial Assi stance for class 1 st to 10 th",
    description: "Educat ional Assi stance of Rs 2500 to the children studying in 1 st to 7 th std. and Rs 5000 for the children stud ying in 8 th std. ti 10 th of the regist ered wor ker.",
    department: "",
    category: "Senior Citizen",
    eligibility: "",
    flare:
      "https://d2w7l1p59qkl0r.cloudfront.net/static/scholarships/banners/document_1675084417.jpg",
    requiredDocuments: "",
    link: "https://setu.pmjay.gov.in/setu/",
    img: "https://th.bing.com/th/id/OIP.fj-VsdrRpZpCNuTHIdSj0QHaEB?pid=ImgDet&rs=1",
  },
  {
    id: 5,
    title: "Pradhan Mantri Jan Arogya Yojana (PM JAY)",
    description: "Pradhan Mantri Shram Yogi Maandhan is a government scheme meant for old age protection and social security of Unorganized workers",
    department: "",
    category: "Kids",
    flare:
      "https://d2w7l1p59qkl0r.cloudfront.net/static/Files/banner/Website-banner-hdfc_rFmCRV.webp",

    eligibility: "",
    requiredDocuments: "",
    link: "https://setu.pmjay.gov.in/setu/",
    img: "https://i2.wp.com/govinfo.me/wp-content/uploads/2017/03/rajasthan-government-logo.png?ssl=1",
  },
];
